# permissions for end users to view streamdata.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: streamdata-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: msm-nc
    app.kubernetes.io/part-of: msm-nc
    app.kubernetes.io/managed-by: kustomize
  name: streamdata-viewer-role
rules:
- apiGroups:
  - mediastreams.media-streaming-mesh.io
  resources:
  - streamdata
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mediastreams.media-streaming-mesh.io
  resources:
  - streamdata/status
  verbs:
  - get
