// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package core

import (
	"github.com/media-streaming-mesh/msm-nc/internal/config"
	node_mapper "github.com/media-streaming-mesh/msm-nc/pkg/node-mapper"
	stream_mapper "github.com/media-streaming-mesh/msm-nc/pkg/stream-mapper"
	"sync"
)

// Injectors from wire.go:

func InitApp() (*App, error) {
	cfg := config.New()
	nodeMapper := node_mapper.InitializeNodeMapper(cfg)
	streamMapper := stream_mapper.NewStreamMapper(cfg.Logger, new(sync.Map))

	app := &App{
		cfg:     cfg,
		nodeMapper: nodeMapper,
		streamMapper: streamMapper,
	}
	return app, nil
}
