// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package core

import (
	"github.com/media-streaming-mesh/msm-k8s/pkg/model"
	node_mapper "github.com/media-streaming-mesh/msm-k8s/pkg/node_mapper"
	"github.com/media-streaming-mesh/msm-nc/internal/config"
	"github.com/media-streaming-mesh/msm-nc/internal/stream_mapper"
	"sync"
)

// Injectors from wire.go:

func InitApp() (*App, error) {
	cfg := config.New()
	nodeMapper := node_mapper.InitializeNodeMapper(cfg.Logger)
	streamMapper := stream_mapper.NewStreamMapper(cfg.Logger, new(sync.Map))

	app := &App{
		cfg:     cfg,
		nodeMapper: nodeMapper,
		streamMapper: streamMapper,
		nodeChan: make(chan model.Node, 1),
	}
	return app, nil
}
